cache = true
max_cache_age = "1d"
max_retries = 3
timeout = 20
accept = [200, 206, 429]
exclude_mail = true

exclude = [
  "^http://localhost",
  "^https://localhost",
  "^https://github.com/MonikaDvorackova/research/issues/new"
]
